class AuthService {
  static Future<String> getAccessToken() async {
    return 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJpYWwiOjEwMDAyODI2LCJwaG9uZSI6Iis5MTg3MTUwODE5NDciLCJ1c2VyaWQiOiI2ZDg4NDNkOS1lMDQ3LTQ0ZmYtODU0Zi1jYjQ0NzkyNjBhYzciLCJmdWxsbmFtZSI6Ik9wZW5zb3J0IGRldiIsImRpc3BsYXluYW1lIjoiT3BlbnNvcnQgZGV2IiwieW9iIjoiMjAwMSIsImdlbmRlciI6Im1hbGUiLCJjb21tdW5pdHkiOiJmYW10cmVlIiwidXNlcnN0YXR1cyI6ImFwcHJvdmVkIiwidHlwZSI6Im1lbWJlciIsImlhdCI6MTcyOTUyMTk1NDIzOSwiZXhwIjoxNzMwMTI2NzU0MjQ3fQ.GkLf11ItjN2LVbHy8pYEzzvldfI2yQ7UPphg0keYSgQ';
  }
}
